// Flat ESLint config. Syntactic (not type-aware): eslint:recommended +
// typescript-eslint recommended, with eslint-config-prettier last to drop
// stylistic rules that would fight a formatter. Type-aware rules (which need
// parserOptions.project) are intentionally off — strict `tsc` already covers
// type correctness; this layer catches obvious bugs (unused vars, unreachable
// code, etc.) without the cost of project-wide type info.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/out/**",
      "**/node_modules/**",
      "**/*.d.ts",
      "packages/core/src/textMetrics.ts", // generated by gen-text-metrics.ts
      "packages/reframe-video/preview/**", // build-copied from packages/preview (untracked)
      "benchmark/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    rules: {
      // allow intentionally-unused names prefixed with _ (e.g. a kept-for-signature arg)
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // standalone Node scripts (build/tooling) run outside the bundler — give them Node globals
    files: ["**/*.{mjs,cjs,mts,cts}", "**/scripts/**"],
    languageOptions: { globals: globals.node },
  },
);
