// Dev tool: measure Inter advance widths with the SAME engine the renderer
// captures with (Playwright/Chromium canvas measureText), so splitText() layout
// matches the actual render exactly. Emits packages/core/src/textMetrics.ts.
//
//   pnpm --filter @reframe/render-cli exec tsx scripts/gen-text-metrics.ts
//
// Lives in render-cli (where playwright resolves). Re-run only when the bundled
// fonts change; the output table is committed.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const WEIGHTS = [400, 700, 800] as const;
const REF = 100; // measure at 100px → widths are "per 100px font-size"
// this file: <root>/packages/render-cli/scripts/ → up 3 to the repo root
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const OUT = join(ROOT, "packages", "core", "src", "textMetrics.ts");

async function fontFaceCss(): Promise<string> {
  const rules = await Promise.all(
    WEIGHTS.map(async (weight) => {
      const data = await readFile(join(ROOT, "assets", "fonts", `inter-${weight}.woff2`));
      return `@font-face { font-family: "Inter"; font-style: normal; font-weight: ${weight}; src: url(data:font/woff2;base64,${data.toString("base64")}) format("woff2"); }`;
    }),
  );
  return rules.join("\n");
}

async function main() {
  const browser = await chromium.launch({ args: ["--force-color-profile=srgb", "--font-render-hinting=none"] });
  try {
    const page = await browser.newPage({ viewport: { width: 100, height: 100 } });
    await page.addStyleTag({ content: await fontFaceCss() });
    await page.evaluate(async () => {
      await Promise.all([...document.fonts].map((f) => f.load()));
      await document.fonts.ready;
    });

    const table = await page.evaluate(
      ({ weights, ref }) => {
        const ctx = document.createElement("canvas").getContext("2d")!;
        const out: Record<number, Record<string, number>> = {};
        for (const w of weights) {
          ctx.font = `${w} ${ref}px Inter`;
          const row: Record<string, number> = {};
          for (let code = 32; code <= 126; code++) {
            const ch = String.fromCharCode(code);
            row[ch] = Math.round(ctx.measureText(ch).width * 100) / 100;
          }
          out[w] = row;
        }
        return out;
      },
      { weights: [...WEIGHTS], ref: REF },
    );

    const fallback: Record<number, number> = {};
    for (const w of WEIGHTS) {
      const vals = Object.values(table[w]!);
      fallback[w] = Math.round((vals.reduce((a, b) => a + b, 0) / vals.length) * 100) / 100;
    }

    const banner =
      "// AUTO-GENERATED by packages/render-cli/scripts/gen-text-metrics.ts — do not edit by hand.\n" +
      "// Inter advance widths in px per 100px font-size, measured with the render engine.\n\n";
    const body =
      `export const INTER_ADVANCE: Record<number, Record<string, number>> = ${JSON.stringify(table, null, 2)};\n\n` +
      `/** Average advance per weight — the fallback for glyphs outside the table. */\n` +
      `export const INTER_FALLBACK: Record<number, number> = ${JSON.stringify(fallback, null, 2)};\n`;
    await writeFile(OUT, banner + body);
    console.log(`wrote ${OUT}\n  weights ${WEIGHTS.join("/")} · 95 glyphs · fallback ${JSON.stringify(fallback)}`);
  } finally {
    await browser.close();
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
