// Product promo: the PRODUCT is the hero (a devicePreset showing real UI); a
// clean figure() walks in and presents it. Every piece — device, UI, character,
// motion — is generated by reframe. figure + characterPreset + devicePreset +
// deviceKit, composed.

import {
  scene, group, ellipse, text,
  seq, par, stagger, tween, wait, oscillate,
  figure, characterPreset, poseTo, devicePreset, deviceScreenPoint,
  cursor, cursorTo, cursorClick,
} from "@reframe/core";
import { heroContent } from "../lib/deviceKit.js";

// the figure standing + presenting (resets the mid-stride walk pose, right arm out)
const PRESENT = { legUpperL: 3, legLowerL: -2, legUpperR: -3, legLowerR: 2, armUpperL: 8, armLowerL: 6, armUpperR: -58, armLowerR: -12 };

const BG = "#0B0F1C";
const ACC = "#FF5A1F";
const CX = 960, CY = 540;

// the "Get started" CTA, mapped from its screen-local spot to scene coords. The
// device is at scale 0.88 by the time the cursor clicks (after the focus push).
// CTA local: inside the hero slot (0,54), at (-w/2+130, h*0.18) = (-362, 102.24).
const CTA = deviceScreenPoint("browser", { x: 1180, y: 452, scale: 0.88 }, [-362, 54 + 102.24]);
const CUR_START: [number, number] = [780, 952];

const ce = (id: string, x: number, y: number, d: number, fill: string, opacity = 1) =>
  ellipse({ id, x, y, width: d, height: d, fill, opacity, anchor: "center" });

// figure layout: starts left, walks to the stop, then presents the device
const FIG_STOP = 560, FIG_Y = 590, FIG_SCALE = 1.18;
const WALK_CYCLES = 4, WALK_TRAVEL = 62;            // 4·62 = 248 px of travel
const FIG_START = FIG_STOP - WALK_CYCLES * WALK_TRAVEL;

export default scene({
  id: "product-promo",
  size: { width: 1920, height: 1080 },
  fps: 30,
  background: BG,
  nodes: [
    // atmospheric backdrop centred on the product
    group({ id: "backdrop", x: 0, y: 0 }, [
      ...Array.from({ length: 14 }, (_, i) => { const t = i / 13; return ce(`glow${i}`, 1170, CY - 30, 1340 - t * 1080, "#15233F", 0.05); }),
      ...Array.from({ length: 7 }, (_, i) => { const t = i / 6; return ce(`acc${i}`, 1170, CY - 60, 700 - t * 520, "#3A2A22", 0.05); }),
    ]),
    ellipse({ id: "fig-shadow", x: FIG_STOP, y: 862, width: 180, height: 26, fill: "#000000", opacity: 0.3, anchor: "center" }),

    // THE PRODUCT — a browser showing a landing page (real UI from deviceKit)
    devicePreset("browser", { id: "device", x: 1180, y: 452, scale: 0.82, opacity: 0, url: "reframe.video", content: heroContent("browser", ACC) }),

    // the presenter — clean figure, accent-matched to the product
    figure({ id: "fig", style: "clean", x: FIG_START, y: FIG_Y, scale: FIG_SCALE, opacity: 0, palette: { accent: ACC } }),

    group({ id: "cap", x: CX, y: 1010, opacity: 0 }, [
      text({ id: "cap-t", x: 0, y: 0, content: "your product, in motion. every frame a reframe render.", fontFamily: "Inter", fontSize: 28, fontWeight: 600, fill: "#7E8AA8", anchor: "center" }),
    ]),

    // the cursor — last, so it draws on top of the product
    cursor({ id: "cur", x: CUR_START[0], y: CUR_START[1], opacity: 0, accent: ACC }),
  ],

  timeline: seq(
    wait(0.3),
    // product enters, then its landing-page UI reveals (deviceKit slots start hidden)
    par(
      tween("device", { opacity: 1 }, { duration: 0.6, ease: "easeOutCubic" }),
      seq(tween("device", { y: 470 }, { duration: 0.01 }), tween("device", { y: 452 }, { duration: 0.7, ease: "easeOutBack" })),
    ),
    stagger(0.15,
      tween("browser-ui-top", { opacity: 1 }, { duration: 0.4, ease: "easeOutCubic" }),
      tween("browser-ui-hero", { opacity: 1 }, { duration: 0.5, ease: "easeOutCubic" }),
    ),
    wait(0.15),
    // figure walks in
    par(
      tween("fig", { opacity: 1 }, { duration: 0.4, ease: "easeOutCubic" }),
      characterPreset("walk", { target: "fig", at: [FIG_START, FIG_Y], cycles: WALK_CYCLES, travel: WALK_TRAVEL, speed: 1.15, label: "walk-in" }),
    ),
    // settle to a stand and present the product + a gentle focus push
    par(
      poseTo("fig", PRESENT, { duration: 0.6, ease: "easeOutCubic" }),
      tween("device", { scale: 0.88 }, { duration: 0.9, ease: "easeInOutCubic" }),
      tween("cap", { opacity: 1, y: 974 }, { duration: 0.6, ease: "easeOutCubic" }),
    ),
    // a cursor glides up to the CTA and clicks it (ripple + the button presses)
    wait(0.3),
    tween("cur", { opacity: 1 }, { duration: 0.3, ease: "easeOutCubic" }),
    cursorTo("cur", CUR_START, CTA),
    cursorClick("cur", { press: "browser-ui-cta", label: "cta-click" }),
    wait(1.8),
  ),

  behaviors: [
    oscillate("fig-chest", "scaleY", { amplitude: 0.012, frequency: 0.6 }, { from: 3.6, ramp: 0.6 }),
    oscillate("fig", "y", { amplitude: 3, frequency: 0.5 }, { from: 3.6, ramp: 0.6 }),
  ],

  // soft CC0 footsteps, one per foot-contact of the walk-in beat. Anchored to the
  // "walk-in" label (survives retiming); offsets follow the gait clock
  // (~0.14s intro + ~0.348s per half-step at speed 1.15, 8 steps).
  audio: {
    cues: [
      ...Array.from({ length: WALK_CYCLES * 2 }, (_, i) => ({
        at: "walk-in",
        offset: 0.14 + (i + 1) * 0.348,
        file: ["footstep_001.ogg", "footstep_002.ogg", "footstep_003.ogg"][i % 3]!,
        gain: 0.34,
      })),
      { at: "cta-click", file: "click_001.ogg", gain: 0.5 }, // the click
    ],
  },
});
